import { useEffect, useState } from 'react';
import { bytes } from '../qbittorrent/api';
import { imageName, request } from './api';

export default function ImageInspector({ item, disabled, onClose, onContainer, onRemove, onPull }) {
  const [detail, setDetail] = useState(null), [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); request(`/docker-api/images/${encodeURIComponent(item.id)}`, { signal: controller.signal }).then(value => { if (!controller.signal.aborted) setDetail(value); }).catch(err => { if (!controller.signal.aborted) setError(err.message); }); return () => controller.abort(); }, [item.id]);
  const row = (name, value) => <div className="dm-kv"><span>{name}</span><strong>{value}</strong></div>;
  return <aside className="dm-panel dm-inspector" aria-label="Selected image"><div className="dm-inspector-head"><button className="qb-icon-button dm-close" aria-label="Close inspector" onClick={onClose}>×</button><p className="eyebrow">SELECTED IMAGE</p><h2>{imageName(item)}</h2><p className="dm-id">{item.id}</p></div><div className="dm-inspector-body">{error && <p className="qb-error" role="alert">{error}</p>}{row('Size', bytes(item.size))}{row('Architecture', detail ? `${detail.os} / ${detail.architecture}` : 'Loading…')}{row('Created', new Date(item.created * 1000).toLocaleString())}{row('Containers', item.containers.length)}{detail && row('Layers', detail.layers)}<p className="eyebrow">TAGS & DIGESTS</p>{[...item.tags, ...item.digests].map(reference => <p className="dm-metadata" key={reference}>{reference}</p>)}{!item.tags.length && !item.digests.length && <p className="dm-note">Untagged image</p>}<p className="eyebrow">USED BY</p>{item.containers.length ? item.containers.map(container => <button className="dm-reference-button" key={container.id} onClick={() => onContainer(container.id)}>{container.name} ↗<small>{container.state}</small></button>) : <p className="dm-note">No running or stopped container references this image.</p>}</div><div className="dm-inspector-actions"><button className="qb-button" disabled={disabled || !item.tags.length} onClick={() => onPull(item.tags[0])}>Pull tag</button><button className="qb-button qb-danger" disabled={disabled || item.containers.length > 0} onClick={() => onRemove([item])}>Remove image</button></div></aside>;
}
